{
 "title": "Crypto mining",
 "time": { "from": "now-3M", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "query": "frser-sqlite-datasource" },
   { "name": "scout_margin", "query": "0.8" },
   { "name": "granularity", "query": "1200" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${database} - Absolute change in value",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "database",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n((SELECT max(balance * usd_price) FROM  coin_value GROUP BY id / 600 ORDER BY datetime DESC LIMIT 1) / (SELECT max(balance * usd_price) FROM coin_value WHERE balance IS NOT NULL GROUP BY id / 600 ORDER BY datetime ASC LIMIT 1)) - 1 as change\nFROM coin_value LIMIT 1",
     "rawQueryText": "SELECT \n((SELECT max(balance * usd_price) FROM  coin_value GROUP BY id / 600 ORDER BY datetime DESC LIMIT 1) / (SELECT max(balance * usd_price) FROM coin_value WHERE balance IS NOT NULL GROUP BY id / 600 ORDER BY datetime ASC LIMIT 1)) - 1 as change\nFROM coin_value LIMIT 1",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "${database} - Next coin",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "repeat": "database",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT p.to_coin_id as other_coin, ((1-0.001*0.001-0.002) * current_coin_price / (sh.target_ratio *(1+(${scout_margin})/100)) / sh.other_coin_price) * 100 as 'percentage' FROM scout_history sh JOIN pairs p ON p.id = sh.pair_id WHERE p.from_coin_id = (SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1) ORDER BY sh.datetime DESC, percentage DESC LIMIT (SELECT count(DISTINCT pairs.to_coin_id) FROM pairs JOIN coins ON coins.symbol = pairs.to_coin_id WHERE coins.enabled = 1 AND pairs.from_coin_id=(SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1))",
     "rawQueryText": "SELECT p.to_coin_id as other_coin, ((1-0.001*0.001-0.002) * current_coin_price / (sh.target_ratio *(1+(${scout_margin})/100)) / sh.other_coin_price) * 100 as 'percentage' FROM scout_history sh JOIN pairs p ON p.id = sh.pair_id WHERE p.from_coin_id = (SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1) ORDER BY sh.datetime DESC, percentage DESC LIMIT (SELECT count(DISTINCT pairs.to_coin_id) FROM pairs JOIN coins ON coins.symbol = pairs.to_coin_id WHERE coins.enabled = 1 AND pairs.from_coin_id=(SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1))",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "% Change in Bridge Value",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "queryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ksh_eth\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "rawQueryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ksh_eth\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS regina_busd\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "rawQueryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS regina_busd\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ren_usdt\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "rawQueryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ren_usdt\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ren_busd\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "rawQueryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ren_busd\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ren_btc\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "rawQueryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ren_btc\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ren_eth\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "rawQueryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ren_eth\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ksh_btc\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "rawQueryText": "SELECT \n    REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, \n    (crypto_trade_amount / (SELECT crypto_trade_amount FROM trade_history ORDER BY datetime ASC LIMIT 1) - 1) AS ksh_btc\nFROM \n    trade_history \nWHERE \n    state='COMPLETE' AND selling=0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  { "title": "${database}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "database" },
  {
   "title": "Progress in Value",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  max(balance * usd_price) AS \"USD value\"\nFROM\n  coin_value\nGROUP BY strftime('%s', datetime) / ${granularity}",
     "rawQueryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  max(balance * usd_price) AS \"USD value\"\nFROM\n  coin_value\nGROUP BY strftime('%s', datetime) / ${granularity}",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  crypto_trade_amount as \"Crypto Trade Value\"\nFROM\n  trade_history\nWHERE\n  state = 'COMPLETE'\n  AND selling = 0",
     "rawQueryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  crypto_trade_amount as \"Crypto Trade Value\"\nFROM\n  trade_history\nWHERE\n  state = 'COMPLETE'\n  AND selling = 0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  max(balance * btc_price) AS \"BTC value\"\nFROM\n  coin_value\nGROUP BY strftime('%s', datetime) / ${granularity}",
     "rawQueryText": "SELECT\n  REPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\n  max(balance * btc_price) AS \"BTC value\"\nFROM\n  coin_value\nGROUP BY strftime('%s', datetime) / ${granularity}",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Next coin",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT p.to_coin_id as other_coin, ((1-0.001*0.001-0.002) * current_coin_price / (sh.target_ratio *(1+0.007)) / sh.other_coin_price) * 100 as 'percentage' FROM scout_history sh JOIN pairs p ON p.id = sh.pair_id WHERE p.from_coin_id = (SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1) ORDER BY sh.datetime DESC, percentage DESC LIMIT (SELECT count(DISTINCT pairs.to_coin_id) FROM pairs JOIN coins ON coins.symbol = pairs.to_coin_id WHERE coins.enabled = 1 AND pairs.from_coin_id=(SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1))",
     "rawQueryText": "SELECT p.to_coin_id as other_coin, ((1-0.001*0.001-0.002) * current_coin_price / (sh.target_ratio *(1+0.007)) / sh.other_coin_price) * 100 as 'percentage' FROM scout_history sh JOIN pairs p ON p.id = sh.pair_id WHERE p.from_coin_id = (SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1) ORDER BY sh.datetime DESC, percentage DESC LIMIT (SELECT count(DISTINCT pairs.to_coin_id) FROM pairs JOIN coins ON coins.symbol = pairs.to_coin_id WHERE coins.enabled = 1 AND pairs.from_coin_id=(SELECT alt_coin_id FROM trade_history ORDER BY datetime DESC LIMIT 1))",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Current Coin",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT  \nalt_coin_id as \"Current coin\", alt_trade_amount as current_coin_amount, \n(SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) ORDER BY datetime DESC LIMIT 1,2) AS last_coin_amount, \n(alt_trade_amount / (SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) ORDER BY datetime DESC LIMIT 1,2) -1 ) AS change \nFROM \ntrade_history \nWHERE\nselling=0 AND alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) \nORDER BY \ndatetime DESC LIMIT 1;",
     "rawQueryText": "SELECT  \nalt_coin_id as \"Current coin\", alt_trade_amount as current_coin_amount, \n(SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) ORDER BY datetime DESC LIMIT 1,2) AS last_coin_amount, \n(alt_trade_amount / (SELECT alt_trade_amount FROM trade_history WHERE alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) ORDER BY datetime DESC LIMIT 1,2) -1 ) AS change \nFROM \ntrade_history \nWHERE\nselling=0 AND alt_coin_id=(SELECT alt_coin_id  FROM trade_history WHERE selling=0 ORDER BY datetime DESC LIMIT 1) \nORDER BY \ndatetime DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Jumps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT (*) FROM trade_history WHERE selling=0",
     "rawQueryText": "SELECT COUNT (*) FROM trade_history WHERE selling=0",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Jumps by coin",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "queryText": "SELECT\nCOUNT(*) as \"Total jumps\",\nalt_coin_id as \"Coin\"\nFROM trade_history \nWHERE selling=0\nGROUP BY alt_coin_id\nORDER BY \"Total jumps\" DESC\n",
     "rawQueryText": "SELECT\nCOUNT(*) as \"Total jumps\",\nalt_coin_id as \"Coin\"\nFROM trade_history \nWHERE selling=0\nGROUP BY alt_coin_id\nORDER BY \"Total jumps\" DESC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Coins progress",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 64 },
   "targets": [
    {
     "queryText": "SELECT \nREPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\nalt_coin_id AS coin, \nalt_trade_amount AS amount\nFROM trade_history\nWHERE state = 'COMPLETE' AND selling = 0",
     "rawQueryText": "SELECT \nREPLACE (datetime, ' ', 'T') || 'Z' AS datetime,\nalt_coin_id AS coin, \nalt_trade_amount AS amount\nFROM trade_history\nWHERE state = 'COMPLETE' AND selling = 0",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Progress",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 64 },
   "targets": [
    {
     "queryText": "SELECT id as trade_id, REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, alt_coin_id AS coin, alt_trade_amount, crypto_trade_amount AS 'USD value' FROM trade_history WHERE selling=0 ORDER BY datetime DESC",
     "rawQueryText": "SELECT id as trade_id, REPLACE (datetime, ' ', 'T') || 'Z' AS datetime, alt_coin_id AS coin, alt_trade_amount, crypto_trade_amount AS 'USD value' FROM trade_history WHERE selling=0 ORDER BY datetime DESC",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  }
 ]
}